import Link from "next/link";
import { notFound } from "next/navigation";

import { ForensicReport } from "@/components/ForensicReport";
import { ErrorNotice, StatusBadge } from "@/components/primitives";
import { TraceTree } from "@/components/TraceTree";
import { getRootCause, getSpans, getTrace } from "@/lib/api";
import { duration, timestamp } from "@/lib/format";

export const dynamic = "force-dynamic";
export const metadata = { title: "Trace · TraceLens" };

export default async function TraceDetailPage({
  params,
}: {
  params: Promise<{ traceId: string }>;
}) {
  const { traceId } = await params;
  const [trace, spans, report] = await Promise.all([
    getTrace(traceId),
    getSpans(traceId),
    getRootCause(traceId),
  ]);

  if (!trace.ok && trace.status === 404) notFound();
  if (!trace.ok) return <ErrorNotice message={trace.error} />;
  if (!spans.ok) return <ErrorNotice message={spans.error} />;

  // A trace can exist without a report — ingested with analysis disabled, or
  // stored before the engine ran. That is a state, not an error.
  const forensics = report.ok ? report.data : null;
  const spanNames = new Map(spans.data.map((span) => [span.span_id, span.name]));
  const synthetic = Boolean(trace.data.attributes?.synthetic);
  // Derived from the spans rather than from the trace's own timestamps.
  // Date parses to whole milliseconds, so a sub-millisecond trace subtracts to
  // exactly 0 and renders as "0µs"; span durations arrive as floats from the
  // API and keep the precision. Using max(end) rather than a sum also keeps
  // the number right when stages ran concurrently.
  const starts = spans.data.map((span) => new Date(span.start_time).getTime());
  const ends = spans.data.map(
    (span, index) => (starts[index] ?? 0) + (span.duration_ms ?? 0),
  );
  const totalMs = spans.data.length ? Math.max(...ends) - Math.min(...starts) : null;

  return (
    <>
      <header className="page-header">
        <Link className="link-row mono" href="/traces">
          ← Traces
        </Link>
        <h1 className="page-title" style={{ marginTop: 8 }}>
          {trace.data.name}
        </h1>
        <div className="row">
          <StatusBadge status={trace.data.status} />
          <span className="mono faint">{trace.data.trace_id}</span>
          <span className="faint">
            {trace.data.project} / {trace.data.pipeline}
          </span>
          <span className="faint">{timestamp(trace.data.start_time)}</span>
          <span className="faint">{duration(totalMs)}</span>
        </div>
      </header>

      {synthetic ? (
        <div className="synthetic-banner">
          Synthetic trace, generated by the benchmark. Not a production measurement.
        </div>
      ) : null}

      <div className="stack">
        {forensics ? (
          <ForensicReport report={forensics} spanNames={spanNames} />
        ) : (
          <div className="notice">
            <p className="notice-title">This trace has not been analysed</p>
            <p className="muted">
              It was stored without running the forensic engine. Analyse it with{" "}
              <span className="mono">POST /api/v1/traces/{traceId}/analyse</span>.
            </p>
          </div>
        )}

        <section>
          <div className="spread" style={{ marginBottom: 10 }}>
            <h2 className="card-title" style={{ fontSize: 15 }}>
              Trace
            </h2>
            <span className="faint mono">
              {spans.data.length} span{spans.data.length === 1 ? "" : "s"}
            </span>
          </div>
          <TraceTree
            spans={spans.data}
            report={forensics}
            defaultOpenSpanId={forensics?.first_divergence_span_id ?? null}
          />
        </section>
      </div>
    </>
  );
}
