"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-03 11:00:58.508423
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "traces",
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("project", sa.String(length=255), nullable=False),
        sa.Column("pipeline", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("trace_id"),
    )
    with op.batch_alter_table("traces", schema=None) as batch_op:
        batch_op.create_index("ix_traces_pipeline_start", ["pipeline", "start_time"], unique=False)
        batch_op.create_index("ix_traces_project_start", ["project", "start_time"], unique=False)
        batch_op.create_index("ix_traces_start_time", ["start_time"], unique=False)
        batch_op.create_index("ix_traces_status_start", ["status", "start_time"], unique=False)

    op.create_table(
        "evaluations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("span_id", sa.String(length=16), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("passed", sa.Integer(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["trace_id"], ["traces.trace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.create_index("ix_evaluations_trace_name", ["trace_id", "name"], unique=False)

    op.create_table(
        "failures",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("span_id", sa.String(length=16), nullable=True),
        sa.Column("detector", sa.String(length=128), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["trace_id"], ["traces.trace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("failures", schema=None) as batch_op:
        batch_op.create_index("ix_failures_category_stage", ["category", "stage"], unique=False)
        batch_op.create_index("ix_failures_trace", ["trace_id"], unique=False)

    op.create_table(
        "root_cause_reports",
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("healthy", sa.Integer(), nullable=False),
        sa.Column("root_cause_span_id", sa.String(length=16), nullable=True),
        sa.Column("root_cause_stage", sa.String(length=32), nullable=True),
        sa.Column("diagnostic_score", sa.Float(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("analysis_ms", sa.Float(), nullable=False),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["trace_id"], ["traces.trace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("trace_id"),
    )
    with op.batch_alter_table("root_cause_reports", schema=None) as batch_op:
        batch_op.create_index(
            "ix_reports_stage_healthy", ["root_cause_stage", "healthy"], unique=False
        )

    op.create_table(
        "spans",
        sa.Column("span_id", sa.String(length=16), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("parent_span_id", sa.String(length=16), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Float(), nullable=True),
        sa.Column("error_type", sa.String(length=255), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_stacktrace", sa.Text(), nullable=True),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("outputs", sa.JSON(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["trace_id"], ["traces.trace_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("span_id"),
    )
    with op.batch_alter_table("spans", schema=None) as batch_op:
        batch_op.create_index("ix_spans_parent", ["parent_span_id"], unique=False)
        batch_op.create_index("ix_spans_stage_status", ["stage", "status"], unique=False)
        batch_op.create_index("ix_spans_trace_sequence", ["trace_id", "sequence"], unique=False)

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("span_id", sa.String(length=16), nullable=False),
        sa.Column("trace_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["span_id"], ["spans.span_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_trace_id"), ["trace_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_trace_id"))

    op.drop_table("events")
    with op.batch_alter_table("spans", schema=None) as batch_op:
        batch_op.drop_index("ix_spans_trace_sequence")
        batch_op.drop_index("ix_spans_stage_status")
        batch_op.drop_index("ix_spans_parent")

    op.drop_table("spans")
    with op.batch_alter_table("root_cause_reports", schema=None) as batch_op:
        batch_op.drop_index("ix_reports_stage_healthy")

    op.drop_table("root_cause_reports")
    with op.batch_alter_table("failures", schema=None) as batch_op:
        batch_op.drop_index("ix_failures_trace")
        batch_op.drop_index("ix_failures_category_stage")

    op.drop_table("failures")
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.drop_index("ix_evaluations_trace_name")

    op.drop_table("evaluations")
    with op.batch_alter_table("traces", schema=None) as batch_op:
        batch_op.drop_index("ix_traces_status_start")
        batch_op.drop_index("ix_traces_start_time")
        batch_op.drop_index("ix_traces_project_start")
        batch_op.drop_index("ix_traces_pipeline_start")

    op.drop_table("traces")
    # ### end Alembic commands ###
